# Generated by Django 2.1.4 on 2018-12-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pe_nome', models.CharField(max_length=50)),
                ('pe_sobrenome', models.CharField(max_length=50)),
                ('pe_idade', models.PositiveIntegerField()),
                ('pe_salario', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pe_bio', models.TextField()),
            ],
        ),
    ]
