# Generated by Django 2.1.4 on 2018-12-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='pe_foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto_cliente'),
        ),
    ]
